// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddMangaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addManga() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1272, 694));
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3) > a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3) > a")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("outlined-basic")).click();
    driver.findElement(By.id("outlined-basic")).sendKeys("Testmanga");
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).click();
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).sendKeys("Testgenre");
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).click();
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).sendKeys("Testzeichner");
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).click();
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).sendKeys("Testautor");
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).click();
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).sendKeys("offen");
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).sendKeys("2023-02-12");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.switchTo().alert().getText(), is("New Manga added"));
    driver.findElement(By.cssSelector(".MuiToolbar-root > .MuiButtonBase-root:nth-child(1) > a")).click();
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector("button")).click();
    driver.switchTo().defaultContent();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3) > a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3) > a")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("outlined-basic")).click();
    driver.findElement(By.id("outlined-basic")).sendKeys("Testmanga");
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).click();
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).sendKeys("Testgenre");
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).click();
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).sendKeys("Testzeichner");
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).click();
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).sendKeys("Testautor");
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).click();
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).sendKeys("offen");
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).click();
    js.executeScript("window.scrollTo(0,189.3333282470703)");
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).sendKeys("2019-03-12");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    assertThat(driver.switchTo().alert().getText(), is("New Manga added"));
  }
}
