package ch.wiss.pruefung_294_295.MangaController;// Generated by Selenium IDE
import org.aspectj.lang.annotation.After;
import org.aspectj.lang.annotation.Before;
import org.junit.jupiter.api.Test;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before("")
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After("")
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1272, 693));
    driver.findElement(By.cssSelector(".navbar-nav > .MuiButtonBase-root:nth-child(1) > a")).click();
    driver.findElement(By.id("outlined-basic")).click();
    driver.findElement(By.id("outlined-basic")).sendKeys("Popcat");
    driver.findElement(By.cssSelector(".makeStyles-root-1")).click();
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".Mui-focused > #outlined-basic")).sendKeys("password");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
  }
}
